export function formatScore(score: number): string {
  if (!score) return ''
  return score.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ')
}

export function parseScoreInput(input: string): number {
  const clean = input.trim().replace(/\s/g, '').replace(/,/g, '').toUpperCase()
  if (!clean) return 0
  if (clean.endsWith('B')) {
    const val = parseFloat(clean.slice(0, -1))
    return isNaN(val) ? 0 : Math.round(val * 1_000_000_000)
  }
  if (clean.endsWith('M')) {
    const val = parseFloat(clean.slice(0, -1))
    return isNaN(val) ? 0 : Math.round(val * 1_000_000)
  }
  if (clean.endsWith('K')) {
    const val = parseFloat(clean.slice(0, -1))
    return isNaN(val) ? 0 : Math.round(val * 1_000)
  }
  const val = parseFloat(clean)
  return isNaN(val) ? 0 : Math.round(val)
}

const LOCALES: Record<string, string> = { fr: 'fr-FR', en: 'en-US', es: 'es-ES', de: 'de-DE' }
export function getLocale(lang: string): string { return LOCALES[lang] ?? 'en-US' }

export function formatDate(dateStr: string, lang: string = 'fr'): string {
  return new Date(dateStr).toLocaleDateString(getLocale(lang), {
    day: '2-digit', month: '2-digit', year: 'numeric',
  })
}

export function getDayName(dateStr: string, lang: string = 'fr'): string {
  return new Date(dateStr).toLocaleDateString(getLocale(lang), { weekday: 'long' })
}

export function toEmailFormat(username: string): string {
  return `${username.toLowerCase().replace(/\s+/g, '_')}@lastwar.internal`
}

export function getRankColor(rank: number): string {
  if (rank === 1) return 'text-yellow-400'
  if (rank === 2) return 'text-slate-300'
  if (rank === 3) return 'text-amber-600'
  return 'text-slate-400'
}

export function getRankBg(rank: number): string {
  if (rank === 1) return 'bg-yellow-400/10 border-yellow-400/30'
  if (rank === 2) return 'bg-slate-300/10 border-slate-300/30'
  if (rank === 3) return 'bg-amber-600/10 border-amber-600/30'
  return ''
}

export type Lang = 'fr' | 'en' | 'es' | 'de'
export type T = typeof TRANSLATIONS.fr

export const LANG_CYCLE: Lang[] = ['fr', 'en', 'es', 'de']
export const LANG_LABELS: Record<Lang, string> = { fr: 'FR', en: 'EN', es: 'ES', de: 'DE' }

export const TRANSLATIONS = {
  fr: {
    title: 'Classement Last War',
    login: 'Connexion',
    logout: 'Déconnexion',
    username: 'Pseudo',
    password: 'Mot de passe',
    birthdate: 'Date de naissance',
    showPassword: 'Afficher',
    hidePassword: 'Masquer',
    rank: 'Rang',
    player: 'Joueur',
    baseScore: 'Base',
    dailyPts: 'Points / Jour',
    contribPts: 'Dim.',
    sanctionPts: 'Sanctions',
    total: 'Total',
    role: 'Rôle',
    pilot: 'Pilote de Train',
    vip: 'VIP',
    weekType: 'Type de semaine',
    pushWeek: 'Semaine Push',
    ecoWeek: 'Semaine Éco',
    pushControlWeek: 'Semaine Push Control',
    freezeDay: 'Geler ce jour',
    unfreezeDay: 'Dégeler ce jour',
    enterScores: 'Saisir les scores',
    contribution: 'Contribution d\'Alliance',
    sanctions: 'Sanctions',
    validateWeek: 'Valider la semaine',
    createUser: 'Créer un compte',
    history: 'Historique',
    dashboard: 'Classement',
    admin: 'Admin',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    close: 'Fermer',
    selectDate: 'Choisir une date',
    vsScore: 'Score VS',
    contribScore: 'Score Contribution',
    sunday: 'Dimanche',
    step: 'Étape',
    top10: 'Top 10 (+10 pts)',
    next10: 'Suivants 10 (+6 pts)',
    last10: 'Derniers 10 (+3 pts)',
    sanctionMinus5: 'Sanction (-5 pts)',
    weekNumber: 'Semaine',
    activeWeek: 'Semaine active',
    noActiveWeek: 'Aucune semaine active',
    startWeek: 'Démarrer la semaine',
    birthday: 'Anniversaire',
    birthdayNote: 'anniversaire(s) cette semaine → places de Pilote réservées',
    pilotNote: '7 premiers → Pilotes de Train',
    vipNote: 'Suivants → VIP',
    weekValidated: 'Semaine validée',
    reopenWeek: 'Rouvrir la semaine',
    selectAll: 'Tout sélectionner',
    deselect: 'Désélectionner',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    weekHistory: 'Historique des semaines',
    noHistory: 'Aucun historique disponible',
    displayName: 'Nom affiché',
    role_admin: 'Administrateur',
    role_reader: 'Lecteur',
    accountType: 'Type de compte',
    eventDs: 'Event DS Vendredi',
    eventDsMyResponse: 'Ma réponse',
    eventDsT1Power: 'Puissance T1',
    statusPresent: 'Présent',
    statusRemplacant: 'Remplaçant',
    statusAbsent: 'Absent',
    eventDsVocal: 'Dispo vocal',
    validate: 'Valider',
    edit: 'Modifier',
    eventDsValidated: 'Réponse validée',
    eventDsSubstitutes: 'Remplaçants',
    eventDsAssignments: 'Répartition des rôles',
    eventDsRecap: 'Récapitulatif des joueurs',
    eventDsNoPlayer: 'Aucun joueur actif lié à ce compte.',
    eventDsBothPresent: 'Impossible d\'être présent aux deux events en même temps.',
    seasonEvents: 'Event Saison',
    seasonEventCreate: 'Créer un event',
    seasonEventName: 'Nom',
    seasonEventDay: 'Jour',
    seasonEventTime: 'Heure',
    seasonEventNone: 'Aucun event créé pour cette semaine.',
    seasonEventPresent: 'Présents',
  },
  en: {
    title: 'Last War Leaderboard',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    birthdate: 'Birthday',
    showPassword: 'Show',
    hidePassword: 'Hide',
    rank: 'Rank',
    player: 'Player',
    baseScore: 'Base',
    dailyPts: 'Daily Pts',
    contribPts: 'Sun.',
    sanctionPts: 'Sanctions',
    total: 'Total',
    role: 'Role',
    pilot: 'Train Pilot',
    vip: 'VIP',
    weekType: 'Week type',
    pushWeek: 'Push Week',
    ecoWeek: 'Eco Week',
    pushControlWeek: 'Push Control Week',
    freezeDay: 'Freeze this day',
    unfreezeDay: 'Unfreeze this day',
    enterScores: 'Enter Scores',
    contribution: 'Alliance Contribution',
    sanctions: 'Sanctions',
    validateWeek: 'Validate Week',
    createUser: 'Create Account',
    history: 'History',
    dashboard: 'Leaderboard',
    admin: 'Admin',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    selectDate: 'Select date',
    vsScore: 'VS Score',
    contribScore: 'Contribution Score',
    sunday: 'Sunday',
    step: 'Step',
    top10: 'Top 10 (+10 pts)',
    next10: 'Next 10 (+6 pts)',
    last10: 'Last 10 (+3 pts)',
    sanctionMinus5: 'Sanction (-5 pts)',
    weekNumber: 'Week',
    activeWeek: 'Active week',
    noActiveWeek: 'No active week',
    startWeek: 'Start week',
    birthday: 'Birthday',
    birthdayNote: 'birthday(s) this week → reserved Pilot spots',
    pilotNote: 'Top 7 → Train Pilots',
    vipNote: 'Next → VIP',
    weekValidated: 'Week validated',
    reopenWeek: 'Reopen week',
    selectAll: 'Select all',
    deselect: 'Deselect',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    weekHistory: 'Week history',
    noHistory: 'No history available',
    displayName: 'Display name',
    role_admin: 'Administrator',
    role_reader: 'Reader',
    accountType: 'Account type',
    eventDs: 'Friday DS Event',
    eventDsMyResponse: 'My response',
    eventDsT1Power: 'T1 Power',
    statusPresent: 'Present',
    statusRemplacant: 'Substitute',
    statusAbsent: 'Absent',
    eventDsVocal: 'Voice available',
    validate: 'Validate',
    edit: 'Edit',
    eventDsValidated: 'Response validated',
    eventDsSubstitutes: 'Substitutes',
    eventDsAssignments: 'Role assignments',
    eventDsRecap: 'Player summary',
    eventDsNoPlayer: 'No active player linked to this account.',
    eventDsBothPresent: 'Cannot be present at both events at once.',
    seasonEvents: 'Season Events',
    seasonEventCreate: 'Create event',
    seasonEventName: 'Name',
    seasonEventDay: 'Day',
    seasonEventTime: 'Time',
    seasonEventNone: 'No event created for this week.',
    seasonEventPresent: 'Present',
  },
  es: {
    title: 'Clasificación Last War',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    username: 'Usuario',
    password: 'Contraseña',
    birthdate: 'Fecha de nacimiento',
    showPassword: 'Mostrar',
    hidePassword: 'Ocultar',
    rank: 'Rango',
    player: 'Jugador',
    baseScore: 'Base',
    dailyPts: 'Pts / Día',
    contribPts: 'Dom.',
    sanctionPts: 'Sanciones',
    total: 'Total',
    role: 'Rol',
    pilot: 'Piloto de Tren',
    vip: 'VIP',
    weekType: 'Tipo de semana',
    pushWeek: 'Semana Push',
    ecoWeek: 'Semana Éco',
    pushControlWeek: 'Semana Push Control',
    freezeDay: 'Congelar este día',
    unfreezeDay: 'Descongelar este día',
    enterScores: 'Ingresar puntos',
    contribution: 'Contribución de Alianza',
    sanctions: 'Sanciones',
    validateWeek: 'Validar semana',
    createUser: 'Crear cuenta',
    history: 'Historial',
    dashboard: 'Clasificación',
    admin: 'Admin',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    close: 'Cerrar',
    selectDate: 'Seleccionar fecha',
    vsScore: 'Puntuación VS',
    contribScore: 'Puntuación Contribución',
    sunday: 'Domingo',
    step: 'Paso',
    top10: 'Top 10 (+10 pts)',
    next10: 'Siguientes 10 (+6 pts)',
    last10: 'Últimos 10 (+3 pts)',
    sanctionMinus5: 'Sanción (-5 pts)',
    weekNumber: 'Semana',
    activeWeek: 'Semana activa',
    noActiveWeek: 'Sin semana activa',
    startWeek: 'Iniciar semana',
    birthday: 'Cumpleaños',
    birthdayNote: 'cumpleaños esta semana → plazas de Piloto reservadas',
    pilotNote: 'Top 7 → Pilotos de Tren',
    vipNote: 'Siguientes → VIP',
    weekValidated: 'Semana validada',
    reopenWeek: 'Reabrir semana',
    selectAll: 'Seleccionar todo',
    deselect: 'Deseleccionar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    weekHistory: 'Historial de semanas',
    noHistory: 'Sin historial disponible',
    displayName: 'Nombre mostrado',
    role_admin: 'Administrador',
    role_reader: 'Lector',
    accountType: 'Tipo de cuenta',
    eventDs: 'Evento DS Viernes',
    eventDsMyResponse: 'Mi respuesta',
    eventDsT1Power: 'Poder T1',
    statusPresent: 'Presente',
    statusRemplacant: 'Suplente',
    statusAbsent: 'Ausente',
    eventDsVocal: 'Disponibilidad de voz',
    validate: 'Validar',
    edit: 'Editar',
    eventDsValidated: 'Respuesta validada',
    eventDsSubstitutes: 'Suplentes',
    eventDsAssignments: 'Asignación de roles',
    eventDsRecap: 'Resumen de jugadores',
    eventDsNoPlayer: 'Ningún jugador activo vinculado a esta cuenta.',
    eventDsBothPresent: 'No se puede estar presente en ambos eventos a la vez.',
    seasonEvents: 'Eventos de Temporada',
    seasonEventCreate: 'Crear evento',
    seasonEventName: 'Nombre',
    seasonEventDay: 'Día',
    seasonEventTime: 'Hora',
    seasonEventNone: 'Ningún evento creado esta semana.',
    seasonEventPresent: 'Presentes',
  },
  de: {
    title: 'Last War Rangliste',
    login: 'Anmelden',
    logout: 'Abmelden',
    username: 'Benutzername',
    password: 'Passwort',
    birthdate: 'Geburtsdatum',
    showPassword: 'Anzeigen',
    hidePassword: 'Verbergen',
    rank: 'Rang',
    player: 'Spieler',
    baseScore: 'Basis',
    dailyPts: 'Pkt. / Tag',
    contribPts: 'So.',
    sanctionPts: 'Strafen',
    total: 'Gesamt',
    role: 'Rolle',
    pilot: 'Zugpilot',
    vip: 'VIP',
    weekType: 'Wochentyp',
    pushWeek: 'Push-Woche',
    ecoWeek: 'Öko-Woche',
    pushControlWeek: 'Push-Control-Woche',
    freezeDay: 'Diesen Tag einfrieren',
    unfreezeDay: 'Diesen Tag auftauen',
    enterScores: 'Punkte eingeben',
    contribution: 'Allianz-Beitrag',
    sanctions: 'Strafen',
    validateWeek: 'Woche validieren',
    createUser: 'Konto erstellen',
    history: 'Verlauf',
    dashboard: 'Rangliste',
    admin: 'Admin',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    close: 'Schließen',
    selectDate: 'Datum wählen',
    vsScore: 'VS-Punkte',
    contribScore: 'Beitragspunkte',
    sunday: 'Sonntag',
    step: 'Schritt',
    top10: 'Top 10 (+10 Pkt.)',
    next10: 'Nächste 10 (+6 Pkt.)',
    last10: 'Letzte 10 (+3 Pkt.)',
    sanctionMinus5: 'Strafe (-5 Pkt.)',
    weekNumber: 'Woche',
    activeWeek: 'Aktive Woche',
    noActiveWeek: 'Keine aktive Woche',
    startWeek: 'Woche starten',
    birthday: 'Geburtstag',
    birthdayNote: 'Geburtstag(e) diese Woche → Pilotenplätze reserviert',
    pilotNote: 'Top 7 → Zugpiloten',
    vipNote: 'Nächste → VIP',
    weekValidated: 'Woche validiert',
    reopenWeek: 'Woche wieder öffnen',
    selectAll: 'Alle auswählen',
    deselect: 'Abwählen',
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    weekHistory: 'Wochenverlauf',
    noHistory: 'Kein Verlauf verfügbar',
    displayName: 'Anzeigename',
    role_admin: 'Administrator',
    role_reader: 'Leser',
    accountType: 'Kontotyp',
    eventDs: 'DS-Event Freitag',
    eventDsMyResponse: 'Meine Antwort',
    eventDsT1Power: 'T1-Stärke',
    statusPresent: 'Anwesend',
    statusRemplacant: 'Ersatz',
    statusAbsent: 'Abwesend',
    eventDsVocal: 'Sprachchat verfügbar',
    validate: 'Bestätigen',
    edit: 'Bearbeiten',
    eventDsValidated: 'Antwort bestätigt',
    eventDsSubstitutes: 'Ersatzspieler',
    eventDsAssignments: 'Rollenverteilung',
    eventDsRecap: 'Spielerübersicht',
    eventDsNoPlayer: 'Kein aktiver Spieler mit diesem Konto verknüpft.',
    eventDsBothPresent: 'Nicht bei beiden Events gleichzeitig anwesend sein.',
    seasonEvents: 'Saison-Events',
    seasonEventCreate: 'Event erstellen',
    seasonEventName: 'Name',
    seasonEventDay: 'Tag',
    seasonEventTime: 'Uhrzeit',
    seasonEventNone: 'Kein Event für diese Woche erstellt.',
    seasonEventPresent: 'Anwesend',
  },
}
